#!/usr/bin/env python3
"""Generate the Stage-4F benchmark world AND its occupancy map from ONE
geometry definition.

The Gazebo world and the map the robot localises against must describe the
same room. Maintaining them as two hand-written files invites silent drift --
a wall moved in the SDF but not the PGM makes AMCL fight the scan, and the
tracker's static-rejection filter (which compares scan points against the map)
starts manufacturing false dynamic tracks out of walls. So both artefacts are
emitted here from `GEOMETRY`, and both are committed.

    make_stage4f_world.py --pkg-dir src/predictive_nav_bringup

Design of the room (see validation/STAGE4F_README.md section 2):
  * 10 x 8 m clear rectangle -- wide enough that the robot's route and a
    +-2.3 m lateral band around it carry ZERO static inflation cost, which is
    the condition Stage-4E could not meet in tb3_sandbox.
  * Four asymmetric pillars near the side walls, purely to give AMCL some
    non-degenerate structure in an otherwise plain rectangle. They are placed
    off every scenario path: >= 1.2 m from the obstacle's crossing column,
    >= 1.0 m from the oblique diagonal, and far enough from the route that
    their inflation stops at |y| = 2.15.
"""
import argparse
import os

RES = 0.05
MAP_MIN = (-6.5, -5.5)      # map origin (world coords of pixel 0,0)
MAP_MAX = (6.5, 5.5)

WALL_T = 0.15               # wall thickness [m]
WALL_H = 0.6                # wall height [m]; LiDAR sits at z ~= 0.18
PILLAR = 0.30               # pillar side [m]

# (name, cx, cy, sx, sy) -- axis-aligned boxes, metres, world frame.
GEOMETRY = [
    ('wall_south', 0.0, -4.0, 10.0 + WALL_T, WALL_T),
    ('wall_north', 0.0, 4.0, 10.0 + WALL_T, WALL_T),
    ('wall_west', -5.0, 0.0, WALL_T, 8.0 + WALL_T),
    ('wall_east', 5.0, 0.0, WALL_T, 8.0 + WALL_T),
    # Asymmetric on purpose: a perfectly symmetric room is a degenerate
    # localisation problem. All four sit at |y| = 3.0, so their inflation
    # (0.15 half-width + 0.70 inflation_radius) stops at |y| = 2.15.
    ('pillar_a', -3.0, 3.0, PILLAR, PILLAR),
    ('pillar_b', 1.2, 3.0, PILLAR, PILLAR),
    ('pillar_c', -1.5, -3.0, PILLAR, PILLAR),
    ('pillar_d', 2.5, -3.0, PILLAR, PILLAR),
]

WORLD_HEADER = """<?xml version="1.0"?>
<!-- GENERATED by scripts/make_stage4f_world.py. Do not edit by hand:
     edit GEOMETRY in that script and re-run, so that this world and
     maps/stage4f_benchmark.pgm stay consistent with each other. -->
<sdf version="1.6" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:arg name="headless" default="true"/>

  <world name="default">
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system"
            name="gz::sim::systems::UserCommands"/>
  <xacro:unless value="$(arg headless)">
    <plugin filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster"/>
  </xacro:unless>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>

    <light name='sun' type='directional'>
      <cast_shadows>0</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <specular>0.8 0.8 0.8 1</specular>
      <attenuation>
        <range>1000</range><constant>0.9</constant>
        <linear>0.01</linear><quadratic>0.001</quadratic>
      </attenuation>
      <direction>-0.5 0.1 -0.9</direction>
    </light>

    <model name='ground_plane'>
      <static>1</static>
      <link name='link'>
        <collision name='collision'>
          <geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry>
          <max_contacts>10</max_contacts>
        </collision>
        <visual name='visual'>
          <geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
      </link>
    </model>

    <scene><shadows>0</shadows></scene>

    <!-- Identical to nav2_minimal_tb3_sim/worlds/tb3_sandbox.sdf.xacro, so
         Stage-4F timing is comparable with Stage-4A..4E. -->
    <physics name='3ms' type='ode'>
      <max_step_size>0.003</max_step_size>
      <real_time_factor>1</real_time_factor>
    </physics>
"""

BOX_TEMPLATE = """
    <model name="{name}">
      <static>1</static>
      <pose>{cx:.4f} {cy:.4f} {hz:.4f} 0 0 0</pose>
      <link name="link">
        <collision name="collision">
          <geometry><box><size>{sx:.4f} {sy:.4f} {sz:.4f}</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>{sx:.4f} {sy:.4f} {sz:.4f}</size></box></geometry>
          <material>
            <ambient>0.35 0.35 0.40 1</ambient>
            <diffuse>0.55 0.55 0.60 1</diffuse>
            <specular>0.1 0.1 0.1 1</specular>
          </material>
        </visual>
      </link>
    </model>
"""


def write_world(path):
    parts = [WORLD_HEADER]
    for name, cx, cy, sx, sy in GEOMETRY:
        parts.append(BOX_TEMPLATE.format(name=name, cx=cx, cy=cy, hz=WALL_H / 2.0,
                                         sx=sx, sy=sy, sz=WALL_H))
    parts.append('\n  </world>\n</sdf>\n')
    with open(path, 'w') as f:
        f.write(''.join(parts))
    return path


def write_map(pgm_path, yaml_path):
    w = int(round((MAP_MAX[0] - MAP_MIN[0]) / RES))
    h = int(round((MAP_MAX[1] - MAP_MIN[1]) / RES))
    FREE, OCC, UNK = 254, 0, 205

    # Everything outside the room is unknown; the room interior is free.
    grid = [[UNK] * w for _ in range(h)]
    inner = (-5.0 + WALL_T / 2.0, -4.0 + WALL_T / 2.0,
             5.0 - WALL_T / 2.0, 4.0 - WALL_T / 2.0)
    for row in range(h):
        wy = MAP_MIN[1] + (row + 0.5) * RES
        for col in range(w):
            wx = MAP_MIN[0] + (col + 0.5) * RES
            if inner[0] <= wx <= inner[2] and inner[1] <= wy <= inner[3]:
                grid[row][col] = FREE

    for _name, cx, cy, sx, sy in GEOMETRY:
        c0 = int((cx - sx / 2.0 - MAP_MIN[0]) / RES)
        c1 = int((cx + sx / 2.0 - MAP_MIN[0]) / RES)
        r0 = int((cy - sy / 2.0 - MAP_MIN[1]) / RES)
        r1 = int((cy + sy / 2.0 - MAP_MIN[1]) / RES)
        for row in range(max(r0, 0), min(r1 + 1, h)):
            for col in range(max(c0, 0), min(c1 + 1, w)):
                grid[row][col] = OCC

    # PGM row 0 is the TOP of the image, i.e. max y.
    data = bytearray()
    for row in range(h - 1, -1, -1):
        data.extend(bytes(grid[row]))
    with open(pgm_path, 'wb') as f:
        f.write(b'P5\n')
        f.write(b'# GENERATED by scripts/make_stage4f_world.py\n')
        f.write(f'{w} {h}\n255\n'.encode())
        f.write(bytes(data))

    with open(yaml_path, 'w') as f:
        f.write(
            '# GENERATED by scripts/make_stage4f_world.py -- do not edit by hand.\n'
            f'image: {os.path.basename(pgm_path)}\n'
            f'resolution: {RES:.6f}\n'
            f'origin: [{MAP_MIN[0]:.6f}, {MAP_MIN[1]:.6f}, 0.000000]\n'
            'negate: 0\n'
            'occupied_thresh: 0.65\n'
            'free_thresh: 0.196\n')
    return w, h


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--pkg-dir', default='src/predictive_nav_bringup')
    args = ap.parse_args()

    worlds = os.path.join(args.pkg_dir, 'worlds')
    maps = os.path.join(args.pkg_dir, 'maps')
    os.makedirs(worlds, exist_ok=True)
    os.makedirs(maps, exist_ok=True)

    world = write_world(os.path.join(worlds, 'stage4f_benchmark.sdf.xacro'))
    w, h = write_map(os.path.join(maps, 'stage4f_benchmark.pgm'),
                     os.path.join(maps, 'stage4f_benchmark.yaml'))
    print(f'wrote {world}')
    print(f'wrote map {w}x{h} px @ {RES} m, origin {MAP_MIN}')
    print(f'room interior: x [-4.925, 4.925], y [-3.925, 3.925]')


if __name__ == '__main__':
    main()
